export const LOME_PLACES = [
  "Cité OUA",
  "Université de Lomé",
  "IPNET",
  "Polytechnique",
  "ESTBA",
  "Agoè",
  "Adidogomé",
  "Bè",
  "Tokoin",
  "Hedzranawoe",
  "Gare routière",
  "Aéroport de Lomé",
  "Nyékonakpoè",
  "Akodessewa",
  "Kodjoviakopé",
  "Avédji",
  "Baguida",
  "Djidjolé",
  "Amoutivé",
  "Agbalépédogan",
  "Grand Marché",
  "Sanguéra",
  "Zanguéra",
  "Klikamé",
  "Adakpamé",
  "Attiegou",
];
